version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: products
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: products of Greenweez with purchasing cost
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: cost of the product

      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of the sale
          - name: orders_id
            description: order in the list
          - name: pdt_id
            description: id of the product
          - name: revenue
            description: value of the sale
          - name: quantity
            description: quantity of products in the order

      - name: ship
        identifier: raw_gz_ship
        description: shipping revenue and costs associated with orders
        columns:
          - name: orders_id
            description: order associated with the shipping revenue and cost
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping revenue
          - name: logcost
            description: logistics cost
          - name: ship_cost
            description: shipping cost
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook data
        columns:
          - name: date_date
            description: order associated with the shipping revenue and cost
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertising cost
          - name: impression
            description: impressions
          - name: click
            description: clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo data
        columns:
          - name: date_date
            description: order associated with the shipping revenue and cost
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertising cost
          - name: impression
            description: impressions
          - name: click
            description: clicks
      - name: bing
        identifier: raw_gz_bing
        description: bing data
        columns:
          - name: date_date
            description: order associated with the shipping revenue and cost
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertising cost
          - name: impression
            description: impressions
          - name: click
            description: clicks
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords data
        columns:
          - name: date_date
            description: order associated with the shipping revenue and cost
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: advertising cost
          - name: impression
            description: impressions
          - name: click
            description: clicks